# Generated by Django 3.0.7 on 2020-06-30 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebInt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webmodel',
            name='creationDate',
        ),
    ]
