# Generated by Django 3.0.7 on 2020-05-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebInt', '0003_webmodel_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmodel',
            name='post',
            field=models.TextField(max_length=200),
        ),
    ]
