# Generated by Django 3.0.7 on 2020-06-30 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.TextField(max_length=40)),
                ('post', models.TextField(max_length=60)),
                ('author', models.TextField(max_length=20)),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
