# Generated by Django 3.0.7 on 2020-06-30 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebInt', '0002_remove_webmodel_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmodel',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
