# Generated by Django 3.0.7 on 2019-02-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebInt', '0005_auto_20190215_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.TextField(max_length=20)),
                ('pasword', models.TextField(max_length=50)),
            ],
        ),
    ]
