# Generated by Django 3.0.7 on 2019-02-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebInt', '0004_auto_20200501_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmodel',
            name='post',
            field=models.TextField(max_length=100000),
        ),
    ]
